`default_nettype none

module vocoder(clk, rst_n, en, mic, saw, out);
// Three-band channel vocoder, matching vocoder_fixed_point.py exactly.
//
//   mic -> 3 bandpass filters -> |.| -> envelope LPF -.
//                                                      \
//                                                       > x -> sum -> out
//                                                      /
//   saw -> the same 3 bandpass filters ----------------'
//
// 16-bit signed throughout: Q1.15 data, Q2.14 coefficients.

    input  wire               clk;
    input  wire               rst_n;
    input  wire               en;        // 1-cycle pulse advances all filters by one sample
    input  wire signed [15:0] mic;
    input  wire signed [15:0] saw;
    output wire signed [15:0] out;

    // FILTER COEFFICIENTS (Q2.14 signed) //
    // Generated by vocoder_fixed_point._design_bandpass; defaults to 0
    // (pass-band off) so an unconfigured instance is silent.

    parameter signed [15:0] B1_b0 = 16'sd0; // band 1
    parameter signed [15:0] B1_b1 = 16'sd0;
    parameter signed [15:0] B1_b2 = 16'sd0;
    parameter signed [15:0] B1_a1 = 16'sd0;
    parameter signed [15:0] B1_a2 = 16'sd0;

    parameter signed [15:0] B2_b0 = 16'sd0; // band 2
    parameter signed [15:0] B2_b1 = 16'sd0;
    parameter signed [15:0] B2_b2 = 16'sd0;
    parameter signed [15:0] B2_a1 = 16'sd0;
    parameter signed [15:0] B2_a2 = 16'sd0;

    parameter signed [15:0] B3_b0 = 16'sd0; // band 3
    parameter signed [15:0] B3_b1 = 16'sd0;
    parameter signed [15:0] B3_b2 = 16'sd0;
    parameter signed [15:0] B3_a1 = 16'sd0;
    parameter signed [15:0] B3_a2 = 16'sd0;

    // Envelope LPF: one-pole IIR, b = [1-alpha, 0], a = [1, -alpha]
    parameter signed [15:0] ENV_b0 = 16'sd0;
    parameter signed [15:0] ENV_a1 = 16'sd0;

    ///////////////////////////////////////

    // Bandpass filters on mic
    wire signed [15:0] bf1_out;
    wire signed [15:0] bf2_out;
    wire signed [15:0] bf3_out;

    // <module name> <instantiation name>(.<portname>(passval), );
    filter #(.b0(B1_b0), .b1(B1_b1), .b2(B1_b2), .a1(B1_a1), .a2(B1_a2))
        bf1(.clk(clk), .rst_n(rst_n), .en(en), .in(mic), .out(bf1_out));
    filter #(.b0(B2_b0), .b1(B2_b1), .b2(B2_b2), .a1(B2_a1), .a2(B2_a2))
        bf2(.clk(clk), .rst_n(rst_n), .en(en), .in(mic), .out(bf2_out));
    filter #(.b0(B3_b0), .b1(B3_b1), .b2(B3_b2), .a1(B3_a1), .a2(B3_a2))
        bf3(.clk(clk), .rst_n(rst_n), .en(en), .in(mic), .out(bf3_out));

    // Rectify by flipping bits and adding 1 (absolute value)
    wire signed [15:0] rect1 = bf1_out[15] ? -bf1_out : bf1_out;
    wire signed [15:0] rect2 = bf2_out[15] ? -bf2_out : bf2_out;
    wire signed [15:0] rect3 = bf3_out[15] ? -bf3_out : bf3_out;

    // Envelope extraction (single one-pole IIR per band)
    wire signed [15:0] e1_out;
    wire signed [15:0] e2_out;
    wire signed [15:0] e3_out;

    filter #(.b0(ENV_b0), .b1(16'sd0), .b2(16'sd0), .a1(ENV_a1), .a2(16'sd0))
        e1(.clk(clk), .rst_n(rst_n), .en(en), .in(rect1), .out(e1_out));
    filter #(.b0(ENV_b0), .b1(16'sd0), .b2(16'sd0), .a1(ENV_a1), .a2(16'sd0))
        e2(.clk(clk), .rst_n(rst_n), .en(en), .in(rect2), .out(e2_out));
    filter #(.b0(ENV_b0), .b1(16'sd0), .b2(16'sd0), .a1(ENV_a1), .a2(16'sd0))
        e3(.clk(clk), .rst_n(rst_n), .en(en), .in(rect3), .out(e3_out));

    // Same bandpass filters on the external sawtooth carrier
    wire signed [15:0] sbf1_out;
    wire signed [15:0] sbf2_out;
    wire signed [15:0] sbf3_out;

    filter #(.b0(B1_b0), .b1(B1_b1), .b2(B1_b2), .a1(B1_a1), .a2(B1_a2))
        sbf1(.clk(clk), .rst_n(rst_n), .en(en), .in(saw), .out(sbf1_out));
    filter #(.b0(B2_b0), .b1(B2_b1), .b2(B2_b2), .a1(B2_a1), .a2(B2_a2))
        sbf2(.clk(clk), .rst_n(rst_n), .en(en), .in(saw), .out(sbf2_out));
    filter #(.b0(B3_b0), .b1(B3_b1), .b2(B3_b2), .a1(B3_a1), .a2(B3_a2))
        sbf3(.clk(clk), .rst_n(rst_n), .en(en), .in(saw), .out(sbf3_out));

    // Multipliers: env_i * filtered_saw_i, truncated Q2.30 -> Q1.15
    wire signed [15:0] mult1_out;
    wire signed [15:0] mult2_out;
    wire signed [15:0] mult3_out;

    /* verilator lint_off UNUSEDSIGNAL */
    wire signed [31:0] prod1 = e1_out * sbf1_out;
    wire signed [31:0] prod2 = e2_out * sbf2_out;
    wire signed [31:0] prod3 = e3_out * sbf3_out;
    /* verilator lint_on UNUSEDSIGNAL */

    assign mult1_out = prod1[30:15];
    assign mult2_out = prod2[30:15];
    assign mult3_out = prod3[30:15];

    // Adder: sum three Q1.15 products with 2-bit growth, truncate to Q1.15
    wire signed [15:0] adder_out;

    /* verilator lint_off UNUSEDSIGNAL */
    wire signed [17:0] sum_wide = {{2{mult1_out[15]}}, mult1_out}
                                + {{2{mult2_out[15]}}, mult2_out}
                                + {{2{mult3_out[15]}}, mult3_out};
    /* verilator lint_on UNUSEDSIGNAL */

    assign adder_out = sum_wide[15:0];

    // Assign output
    assign out = adder_out;

endmodule
